# Generated by Django 3.2 on 2021-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=60)),
                ('nota1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('nota2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('nota3', models.DecimalField(decimal_places=0, max_digits=2)),
                ('nota4', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
